text = " "
print "", text.center(70, "-") + "" 
text = "Vault Tec"
print "|", text.center(70, " ") + "|" 
text =  "" 
print "|", text.ljust(70," ") + "|"
text =  "Anton Teljutsenko" 
print "|", text.center(70," ") + "|"
text =  "juhataja" 
print "|", text.center(70," ") + "|"
text =  "" 
print "|", text.ljust(70," ") + "|"
text =  "Elukoht: Voru Vald, Navi Kula, Uue Koroli Talu" 
print "|", text.ljust(70," ") + "|"
text =  "Tel:59086859" 
print "|", text.ljust(70," ") + "|"
text =  "Email:Anton4e7@hotmail.com" 
print "|", text.ljust(70," ") + "|"
text =  "Ettevotte Email:VaultTec@Vautltec.com" 
print "|", text.ljust(70," ") + "|"
text = " "
print "", text.center(70, "-") + "" 
