text = " "
print "", text.center(70, "-") + "" 
text = "Programeerimine"
print "|", text.center(70, " ") + "|" 
text =  "" 
print "|", text.ljust(70," ") + "|"
text =  "" 
print "|", text.ljust(70," ") + "|"
text =  "Uudiskiri | November 2013" 
print "|", text.rjust(70," ") + "|"
text =  "" 
print "|", text.ljust(70," ") + "|"
text =  "" 
print "|", text.ljust(70," ") + "|"
text =  "Lugupeetud Ragnar Kurm!" 
print "|", text.ljust(70," ") + "|"
text =  "" 
print "|", text.ljust(70," ") + "|"
text =  "Tahan teavitada, et kuupaeval 06.11.2013 ehk"
print "|", text.ljust(70," ") + "|"
text = "tanaseks tuuniks mina ei suutnud kodutood valmistada."
print "|", text.ljust(70," ") + "|"
text =  "Selle pohjusek on see,et mul ei onnestunud paigaldada"
print "|", text.ljust(70," ") + "|"
text = "oma kodu arvutile Ubuntu. "
print "|", text.ljust(70," ") + "|"
text =  "" 
print "|", text.ljust(70," ") + "|"
text =  "" 
print "|", text.ljust(70," ") + "|"
text =  "Anton Teljutsenko" 
print "|", text.ljust(70," ") + "|"
text =  "AAp-11" 
print "|", text.ljust(70," ") + "|"
text =  "VKHK" 
print "|", text.ljust(70," ") + "|"
text = " "
print "", text.center(70, "-") + "" 
